version: '3.8'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
